import os

# AWS Configuration
# The region where resources will be scanned and cleaned.
AWS_REGION = "us-east-1"

# Report Configuration
# Absolute path to the report file where resources are listed.
# This file is generated by the Reader and used by the Cleaner.
REPORT_FILE_PATH = r"C:\Users\CR1001\OneDrive\Desktop\aws-services-app\scripts\aws_resource_cleaner\aws-services-reader.md"

# Credentials Note:
# These scripts use the standard AWS SDK (boto3) credential chain.
# They look for credentials in the following order:
# 1. Environment Variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)
# 2. Shared Credentials File (~/.aws/credentials)
# 3. IAM Role (if running on EC2/Lambda)
# 
# You do NOT need to hardcode credentials here. Ensure your environment is configured properly
# (e.g., run `aws configure` in your terminal).
